### PR TITLE
New Bech Commands

### PR DESCRIPTION
**Pull request by nothingalike**
first commit has the bech decoding. encoding is next. Also depends on the .NET upgrade PR

### CODE REVIEW

**Comment by nothingalike** [comment]
Depends on #1

**Comment by safestak-keith** [comment]
@nothingalike I noticed this peculiar case. Off the top of your head do you know what could be causing `Bech32.IsValid(Value)` to think it is an invalid bech32 encoded value? I generated a valid bech32 encoded extended payment key which I double-checked to be the same as the `cardano-address` output.

```console
$ cscli bech32 decode --value addr_xsk1fzw9r482t0ekua7rcqewg3k8ju5d9run4juuehm2p24jtuzz4dg4wpeulnqhualvtx9lyy7u0h9pdjvmyhxdhzsyy49szs6y8c9zwfp0eqyrqyl290e6dr0q3fvngmsjn4aask9jjr6q34juh25hczw3euust0dw

Invalid option --value addr_xsk1fzw9r482t0ekua7rcqewg3k8ju5d9run4juuehm2p24jtuzz4dg4wpeulnqhualvtx9lyy7u0h9pdjvmyhxdhzsyy49szs6y8c9zwfp0eqyrqyl290e6dr0q3fvngmsjn4aask9jjr6q34juh25hczw3euust0dw is not a valid bech32 encoding.
```

**Comment by safestak-keith** [comment]
Implemented the Blake2bHashCommand which allows you to do the following nifty things with cscli:
 - Deriving addresses manually from the verification key
 - Deriving policyIds from the policy script 
 - Deriving assetIds from the policyId and assetname
 - Deriving the transactionHash from the tx body

**Comment by nothingalike** [comment]
@safestak-keith i compared the bech encoding and decoding to what is in the cardanosharp-wallet tests and everything was encoding/decoding correctly!

LGTM

**Pull request merged**
